services:
  netcup-ddns:
    build: .
    container_name: netcup-ddns
    restart: unless-stopped
    env_file:
      - .env
#      UPDATE_INTERVAL: 300    # optional: Logs auf stdout
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
